### PR TITLE
fix encoding of cyrillic-filenames

### PR DESCRIPTION
**Pull request by ildarkhasanshin**

### CODE REVIEW

**Comment by Alexey-T** [comment]
@pohmelie I don't understand this patch. some unknown python for me - `__class__`. is it OK for you?

**Comment by ildarkhasanshin** [comment]
> is it OK for you?

yes

before
image

after
image

**Comment by Alexey-T** [comment]
Ildar, does it work on Win? it may have different codepage, not UTF8.

**Comment by ildarkhasanshin** [comment]
да, тестировал на русскоязычном вин7 - все норм

**Pull request merged**
